on:
  schedule:
    - cron: "0 7,11,15,19,23 * * *"   # UTC
jobs:
  ping-update-endpoint:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/update on Production
        env:
          SITE_URL: https://www.wordiagram.com
          BASIC_USER: ${{ secrets.BASIC_AUTH_USER }}
          BASIC_PASS: ${{ secrets.BASIC_AUTH_PASS }}
        run: |
          set -euo pipefail
          curl -sS -X POST "$SITE_URL/api/update" \
            -u "$BASIC_USER:$BASIC_PASS" \
            -H "Content-Type: application/json" \
            --data '{"kind":"both"}' \
            -w "\nHTTP %{http_code}\n"
